### ISSUE TITLE
Can't run golangci-lint: invalid output json, see build log

### ISSUE THREAD

**Issue by vthiery** [golangci/golangci-worker#54]
We're getting when golangci scans our repositories, with the following logs:
```
GOLANGCI_COM_RUN=1 golangci-lint run --out-format=json --issues-exit-code=0 --deadline=5m --new=false --new-from-rev= --new-from-patch=../changes.patch
    Flag --deadline has been deprecated, flag will be removed soon, please, use .golangci.yml config
    {"Issues":null,"Report":{"Linters":[{"Name" [...]
```
I guess the output containing the non-JSON line `  Flag --deadline has been deprecated, flag will be removed soon, please, use .golangci.yml ` is problematic. 

I raised the PR https://github.com/golangci/golangci-worker/pull/53 to attempt to fix the issue. I also updated the flag in golangci-api with https://github.com/golangci/golangci-api/pull/152.

**Comment by jirfag** [comment]
fixed and released, thank you!

please, check

**Comment by vthiery** [comment]
I'm actually still getting this error. Could it be that the container golangci/build-runner was not updated?

**Comment by vthiery** [comment]
It just got updated (cf https://hub.docker.com/r/golangci/build-runner/tags) and the scans now work. So all good :)
